on:
  workflow_dispatch:

name: Use other action

jobs:
  hello:
    name: Use other action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello
        uses: npv2k1/npv2k1@master

